'use client'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
type Selection = { mode: 'ids'; contactIds: string[] } | { mode: 'filter'; q?: string; gender?: string; labelId?: string; excludeIds?: string[] }
export function CampaignForm() { const router = useRouter(); const [selection, setSelection] = useState<Selection | null>(null); const [name, setName] = useState(''); const [neutralMessage, setNeutralMessage] = useState(''); const [maleMessage, setMaleMessage] = useState(''); const [femaleMessage, setFemaleMessage] = useState(''); const [mediaPath, setMediaPath] = useState(''); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false)
  // Restore the explicit selection handoff from Contacts once on mount.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { const raw = window.sessionStorage.getItem('nyx-campaign-selection'); if (raw) setSelection(JSON.parse(raw) as Selection) }, [])
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!selection) { setError('Selecciona contactos desde Contactos antes de crear la campaña.'); return } setSaving(true); const response = await fetch('/api/campaigns', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name, neutralMessage, maleMessage: maleMessage || undefined, femaleMessage: femaleMessage || undefined, mediaPath: mediaPath || undefined, selection }) }); const body = await response.json().catch(() => ({})); if (!response.ok) setError(body.error === 'EMPTY_AUDIENCE' ? 'La audiencia está vacía.' : 'No fue posible crear la campaña.'); else { window.sessionStorage.removeItem('nyx-campaign-selection'); router.push('/app/campaigns') } setSaving(false) }
  return <form className="card stack form-narrow" onSubmit={(event) => void submit(event)}>{error && <div className="error">{error}</div>}<p><strong>Audiencia:</strong> {selection ? selection.mode === 'ids' ? `${selection.contactIds.length} contactos seleccionados` : 'Todos los resultados filtrados' : 'No seleccionada'} </p><label>Nombre opcional<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Mensaje neutral<textarea required rows={5} value={neutralMessage} onChange={(event) => setNeutralMessage(event.target.value)} /></label><label>Variante hombre opcional<textarea rows={4} value={maleMessage} onChange={(event) => setMaleMessage(event.target.value)} /></label><label>Variante mujer opcional<textarea rows={4} value={femaleMessage} onChange={(event) => setFemaleMessage(event.target.value)} /></label><label>Imagen opcional (URL HTTPS de Storage)<input type="url" value={mediaPath} onChange={(event) => setMediaPath(event.target.value)} /></label><button disabled={saving}>{saving ? 'Guardando…' : 'Previsualizar y encolar'}</button></form> }
