'use client'
import { useEffect, useState } from 'react'
type Label = { id: string; name: string; color?: string | null; contact_labels?: Array<{ count: number }> }
export function LabelsWorkspace() { const [labels, setLabels] = useState<Label[]>([]); const [name, setName] = useState(''); const [color, setColor] = useState(''); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null)
  async function load() { const response = await fetch('/api/labels'); const body = await response.json(); if (response.ok) setLabels(body.labels ?? []); else setError('No fue posible cargar labels.') }
  // The initial client fetch hydrates this workspace from the owner-scoped API.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load() }, [])
  async function create(event: React.FormEvent) { event.preventDefault(); const response = await fetch('/api/labels', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name, color: color || undefined }) }); if (!response.ok) setError('No fue posible crear el label.'); else { setName(''); setColor(''); setMessage('Label creado.'); await load() } }
  async function edit(label: Label) { const next = window.prompt('Nombre del label', label.name)?.trim(); if (!next) return; const response = await fetch(`/api/labels/${label.id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: next, color: label.color }) }); if (response.ok) await load(); else setError('No fue posible editar el label.') }
  async function remove(label: Label) { const count = label.contact_labels?.[0]?.count ?? 0; if (!window.confirm(`Eliminar ${label.name}? Se desasociará de ${count} contactos.`)) return; const response = await fetch(`/api/labels/${label.id}`, { method: 'DELETE' }); if (response.ok) { setMessage('Label eliminado.'); await load() } else setError('No fue posible eliminar el label.') }
  return <div className="stack">{error && <div className="error">{error}</div>}{message && <div className="success">{message}</div>}<form className="card row" onSubmit={(event) => void create(event)}><input required placeholder="Nombre" value={name} onChange={(event) => setName(event.target.value)} /><input placeholder="#RRGGBB opcional" value={color} onChange={(event) => setColor(event.target.value)} /><button>Crear label</button></form><div className="label-library">{labels.map((label) => <article className="card label-library-row" key={label.id}><span className="label-chip" style={label.color ? { borderColor: label.color } : undefined}>{label.name}</span><span>{label.contact_labels?.[0]?.count ?? 0} contactos</span><button className="secondary" onClick={() => void edit(label)}>Editar</button><button className="secondary" onClick={() => void remove(label)}>Eliminar</button></article>)}{!labels.length && <p>No hay labels todavía.</p>}</div></div> }
